CREATE TABLE CUSTOMER(
    EmployeeID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(64) NOT NULL,
    PhoneNr VARCHAR(16) NOT NULL
);

INSERT INTO CUSTOMER(FirstName, LastName, PhoneNr)
VALUES
_inserts_